import { useState } from 'react';
import {
  ShieldCheck,
  FileCheck,
  Code,
  CheckCircle,
  XCircle,
  Hash,
  Eye,
  Lock,
} from 'lucide-react';

const AuditCenterView = () => {
  const [selectedProof, setSelectedProof] = useState(null);

  const tallies = [
    { id: 'TALLY-4091', poll: 'Student Council 2024', status: 'Computed', computedAt: '2024-03-12 10:00', proofId: 'MP-991A' },
    { id: 'TALLY-4092', poll: 'Budget Review', status: 'Verifying', computedAt: '2024-03-12 11:30', proofId: 'MP-992B' },
  ];

  const proofData = {
    id: 'MP-991A',
    is_verified: true,
    protocol: 'Groth16',
    curve: 'bn128',
    public_signals: [
      "0x00000000000000000000000000000000000000000000000000000000000001bc",
      "0x2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c"
    ],
    proof_json: `{\n  "pi_a": ["0x12..", "0x34..", "0x01.."],\n  "pi_b": [\n    ["0x56..", "0x78.."],\n    ["0x9a..", "0xbc.."]\n  ],\n  "pi_c": ["0xde..", "0xf0..", "0x01.."]\n}`
  };

  return (
    <div className="space-y-6 animate-in fade-in duration-300">

      <div className="bg-gradient-to-r from-emerald-900 to-teal-900 rounded-2xl p-6 sm:p-8 border border-emerald-800 shadow-xl text-white relative overflow-hidden">
        <div className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-1/4 opacity-10 hidden sm:block">
          <ShieldCheck size={250} />
        </div>
        <div className="relative z-10">
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight mb-2">Cryptographic Audit Center</h2>
          <p className="text-emerald-100/80 max-w-xl text-xs sm:text-sm leading-relaxed">
            Verify election integrity without compromising voter privacy. Inspect Merkle Proofs generated by the tallying circuit to guarantee the accuracy of results.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div className="lg:col-span-1 bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden flex flex-col h-[550px]">
          <div className="p-4 border-b border-slate-100 bg-slate-50 font-bold text-slate-800 flex items-center gap-2">
            <FileCheck size={18} className="text-emerald-600" />
            Tally Operations
          </div>
          <div className="flex-1 overflow-auto p-4 space-y-3">
            {tallies.map((tally) => (
              <div
                key={tally.id}
                onClick={() => setSelectedProof(proofData)}
                className={`p-4 rounded-xl border cursor-pointer transition-all ${selectedProof?.id === tally.proofId ? 'border-emerald-500 bg-emerald-50 shadow-sm' : 'border-slate-200 hover:border-emerald-300 hover:shadow-sm bg-white'}`}
              >
                <div className="flex justify-between items-start mb-2">
                  <span className="text-xs font-mono font-bold text-slate-500">{tally.id}</span>
                  <span className={`text-[10px] font-bold px-2 py-0.5 rounded uppercase tracking-wider ${tally.status === 'Computed' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>
                    {tally.status}
                  </span>
                </div>
                <h4 className="font-bold text-slate-800 text-sm mb-1">{tally.poll}</h4>
                <div className="flex items-center gap-2 text-xs text-slate-500">
                  <Hash size={12} /> Proof: {tally.proofId}
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="lg:col-span-2 bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden flex flex-col h-[550px]">
          {selectedProof ? (
            <>
              <div className="p-6 border-b border-slate-100 bg-slate-50 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                  <h3 className="font-bold text-lg text-slate-800 flex items-center gap-2">
                    <Lock size={20} className="text-slate-400" />
                    Proof Inspector: <span className="font-mono text-emerald-600">{selectedProof.id}</span>
                  </h3>
                  <p className="text-xs text-slate-500 mt-1">Protocol: {selectedProof.protocol} | Curve: {selectedProof.curve}</p>
                </div>

                <div className={`flex items-center gap-3 px-4 sm:px-5 py-3 rounded-xl border w-full sm:w-auto justify-center sm:justify-start ${selectedProof.is_verified ? 'bg-emerald-50 border-emerald-200' : 'bg-rose-50 border-rose-200'}`}>
                  {selectedProof.is_verified ? (
                    <>
                      <CheckCircle size={28} className="text-emerald-500 shrink-0" />
                      <div>
                        <p className="text-sm font-bold text-emerald-800 uppercase tracking-wide">Valid Proof</p>
                        <p className="text-[10px] text-emerald-600">Cryptographically sound</p>
                      </div>
                    </>
                  ) : (
                    <>
                      <XCircle size={28} className="text-rose-500 shrink-0" />
                      <div>
                        <p className="text-sm font-bold text-rose-800 uppercase tracking-wide">Invalid Proof</p>
                        <p className="text-[10px] text-rose-600">Verification failed</p>
                      </div>
                    </>
                  )}
                </div>
              </div>

              <div className="px-6 py-4 bg-white border-b border-slate-100 flex flex-col sm:flex-row items-center gap-3 justify-end">
                <button
                  className="flex items-center justify-center gap-2 px-4 py-2 w-full sm:w-auto bg-white border border-rose-200 text-rose-600 hover:bg-rose-50 rounded-lg text-sm font-medium transition shadow-sm"
                  onClick={() => alert('Tally Rejected. Further investigation required.')}
                >
                  <XCircle size={16} /> Reject Tally
                </button>
                <button
                  className="flex items-center justify-center gap-2 px-4 py-2 w-full sm:w-auto bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg text-sm font-medium transition shadow-sm disabled:opacity-50"
                  disabled={!selectedProof.is_verified}
                  onClick={() => alert('Tally officially approved and finalized.')}
                >
                  <CheckCircle size={16} /> Approve & Finalize Tally
                </button>
              </div>

              <div className="flex-1 overflow-auto bg-[#0a0a0a] text-emerald-400 font-mono text-xs p-6 space-y-6">
                <div>
                  <h4 className="flex items-center gap-2 text-slate-400 mb-2 border-b border-slate-800 pb-2">
                    <Eye size={14} /> Public Signals (Inputs/Outputs)
                  </h4>
                  {selectedProof.public_signals.map((sig, i) => (
                    <div key={i} className="break-all bg-[#1a1a1a] p-2 rounded mb-2 border border-[#2a2a2a] pl-4 relative">
                      <span className="absolute left-0 top-0 bottom-0 w-1 bg-emerald-700/50 rounded-l"></span>
                      {sig}
                    </div>
                  ))}
                </div>

                <div>
                  <h4 className="flex items-center gap-2 text-slate-400 mb-2 border-b border-slate-800 pb-2">
                    <Code size={14} /> Raw Vector Data (Merkle Path)
                  </h4>
                  <pre className="text-emerald-300 overflow-auto bg-[#1a1a1a] p-4 rounded-lg border border-[#2a2a2a]">
                    {selectedProof.proof_json}
                  </pre>
                </div>
              </div>
            </>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-slate-400 p-8 text-center bg-slate-50/50">
              <ShieldCheck size={48} className="mb-4 text-slate-300" />
              <p className="text-base font-medium text-slate-600 mb-1">No Tally Selected</p>
              <p className="text-sm">Select an operation from the list to inspect its Merkle proof components.</p>
            </div>
          )}
        </div>
      </div>

    </div>
  );
};

export default AuditCenterView;
